FirstInstance:
  MachineKeyPath:
  InstanceName: ZITADEL
  DefaultLanguage: en
  Org:
    Name: ZITADEL
    Human:
      # in case that UserLoginMustBeDomain is false (default) and you don't overwrite the username with an email,
      # it will be suffixed by the org domain (org-name + domain from config).
      # for example: zitadel-admin in org ZITADEL on domain.tld -> zitadel-admin@zitadel.domain.tld
      UserName: zitadel-admin
      FirstName: ZITADEL
      LastName: Admin
      NickName:
      DisplayName:
      Email:
        Address: #uses the username if empty
        Verified: true
      PreferredLanguage: en
      Gender:
      Phone:
        Number:
        Verified:
      Password: Ready.set.g0
      # Do not require password change on the first login
      PasswordChangeRequired: false
    Machine:
      Machine:
        Username: zitadel-admin-sa
        Name: Admin
      MachineKey:
        Type: 1